sudo: required

language: C

matrix:
  include:
    - compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: COMPILER=gcc-6
    - compiler: clang-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env: COMPILER=clang-3.9

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpari-dev

script:
  - cd lib/parson
  - make libparson.a
  - cd ../..
  - mv lib/parson/libparson.a lib/libparson.a
  - make