os: linux
dist: focal
language: c
jobs:
  include:
    - compiler: gcc-9
    - compiler: clang-10
      addons:
        apt:
          packages:
            - clang-10
            - llvm-10-dev
            - lld-10

before_install:
  - sudo apt-get update
  - sudo apt-get install -y dpkg apt
  - wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/p/pari/libpari-gmp-tls7_2.13.1-1_amd64.deb
  - wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/p/pari/libpari-dev_2.13.1-1_amd64.deb
  - wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/p/pari/pari-gp_2.13.1-1_amd64.deb
  - wget https://mirrors.edge.kernel.org/ubuntu/pool/main/r/readline/libreadline8_8.0-4_amd64.deb
  - wget https://mirrors.edge.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo6_6.2-1_amd64.deb
  - wget https://pari.math.u-bordeaux.fr/pub/pari/packages/seadata.tgz
  - sudo dpkg --force-all -i libtinfo6_6.2-1_amd64.deb libreadline8_8.0-4_amd64.deb libpari-gmp-tls7_2.13.1-1_amd64.deb libpari-dev_2.13.1-1_amd64.deb pari-gp_2.13.1-1_amd64.deb
  - DATADIR=$(echo "default(datadir)" | gp -q | cut -d\" -f2)
  - sudo tar --strip-components=1 -C ${DATADIR} -xzvf seadata.tgz data/

script: # Test, clean, build for release
  - TEST=1 make unittest
  - TEST=1 make clean-all
  - make -j2

after_success:
  - bash <(curl -s https://codecov.io/bash)


