sudo: required

language: C

matrix:
  include:
    - compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
    - compiler: clang-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9

before_install:
  - wget mirrors.kernel.org/ubuntu/pool/universe/p/pari/libpari-gmp-tls5_2.9.1-1_amd64.deb
  - wget mirrors.kernel.org/ubuntu/pool/universe/p/pari/libpari-dev_2.9.1-1_amd64.deb
  - sudo dpkg --force-all -i libpari-gmp-tls5_2.9.1-1_amd64.deb libpari-dev_2.9.1-1_amd64.deb

script:
  - cd lib/parson
  - make libparson.a
  - cd ../..
  - mv lib/parson/libparson.a lib/libparson.a
  - make
