name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: [gcc, clang]
    env:
      CC: ${{ matrix.CC }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup pari
        run: |
          sudo apt-get update
          sudo apt-get install -y libpari-dev pari-gp pari-seadata meson ninja-build
      - name: Test
        run: |
          TEST=1 make unittest
      - name: Code coverage
        if: ${{ matrix.CC == 'gcc' }}
        run: |
          cd src && find . -name "*.gcda" -exec gcov -pb "{}" +;
      - name: Code coverage upload
        uses: codecov/codecov-action@v4
        if: ${{ matrix.CC == 'gcc' }}
        with:
          env_vars: CC
          token: ${{ secrets.CODECOV_TOKEN }}
